global:
  client: xfreerdp
  connection_string: sqlite:///myrdp.sqlite
  log_level: debug

xfreerdp:
  executable: xfreerdp
  args: "+clipboard /cert-ignore +drives /kbd:0x00000415 -themes +compression /gdi:sw +auto-reconnect"

rdesktop:
  executable: rdesktop
  args: ""
